-- TaskFlow initial schema
-- All timestamps stored in UTC (TIMESTAMPTZ)
-- Soft deletes via deleted_at (null = not deleted)
-- UUIDs generated by PostgreSQL gen_random_uuid()

-- ── Users ─────────────────────────────────────────────────────────────────────

CREATE TABLE users (
    id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    email        VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name    VARCHAR(255) NOT NULL,
    avatar_url   VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at   TIMESTAMPTZ
);

CREATE INDEX idx_users_email      ON users (email);
CREATE INDEX idx_users_active     ON users (id) WHERE deleted_at IS NULL;

-- ── Teams ─────────────────────────────────────────────────────────────────────

CREATE TABLE teams (
    id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    name       VARCHAR(255) NOT NULL,
    slug       VARCHAR(255) NOT NULL UNIQUE,
    owner_id   UUID         NOT NULL REFERENCES users (id),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_teams_slug       ON teams (slug);
CREATE INDEX idx_teams_owner_id   ON teams (owner_id);
CREATE INDEX idx_teams_active     ON teams (id) WHERE deleted_at IS NULL;

-- ── Team Memberships ──────────────────────────────────────────────────────────

CREATE TABLE team_memberships (
    team_id   UUID        NOT NULL REFERENCES teams (id),
    user_id   UUID        NOT NULL REFERENCES users (id),
    role      VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (team_id, user_id),
    CONSTRAINT chk_membership_role CHECK (role IN ('OWNER', 'MEMBER', 'VIEWER'))
);

CREATE INDEX idx_team_memberships_user_id ON team_memberships (user_id);

-- ── Projects ──────────────────────────────────────────────────────────────────

CREATE TABLE projects (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id     UUID         NOT NULL REFERENCES teams (id),
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT chk_project_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE INDEX idx_projects_team_id   ON projects (team_id);
CREATE INDEX idx_projects_status    ON projects (status);
CREATE INDEX idx_projects_active    ON projects (team_id) WHERE deleted_at IS NULL;

-- ── Tasks ─────────────────────────────────────────────────────────────────────

CREATE TABLE tasks (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id  UUID         NOT NULL REFERENCES projects (id),
    title       VARCHAR(500) NOT NULL,
    description TEXT,
    status      VARCHAR(20)  NOT NULL DEFAULT 'BACKLOG',
    priority    VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    assignee_id UUID         REFERENCES users (id),
    due_date    DATE,
    created_by  UUID         NOT NULL REFERENCES users (id),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT chk_task_status   CHECK (status IN ('BACKLOG','TODO','IN_PROGRESS','IN_REVIEW','DONE','CANCELLED')),
    CONSTRAINT chk_task_priority CHECK (priority IN ('LOW','MEDIUM','HIGH','CRITICAL'))
);

CREATE INDEX idx_tasks_project_id          ON tasks (project_id);
CREATE INDEX idx_tasks_assignee_id         ON tasks (assignee_id);
CREATE INDEX idx_tasks_status              ON tasks (status);
CREATE INDEX idx_tasks_priority            ON tasks (priority);
CREATE INDEX idx_tasks_created_at          ON tasks (created_at);
-- Composite index for the most common query: active tasks per project filtered by status
CREATE INDEX idx_tasks_project_status_active ON tasks (project_id, status) WHERE deleted_at IS NULL;
-- Supports "my tasks" view: tasks assigned to a user in a given status
CREATE INDEX idx_tasks_assignee_status_active ON tasks (assignee_id, status) WHERE deleted_at IS NULL;

-- ── Labels ────────────────────────────────────────────────────────────────────

CREATE TABLE labels (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID        NOT NULL REFERENCES projects (id),
    name       VARCHAR(100) NOT NULL,
    color      VARCHAR(7)  NOT NULL, -- hex: #RRGGBB
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (project_id, name)
);

CREATE INDEX idx_labels_project_id ON labels (project_id);

-- ── Task Labels (join) ────────────────────────────────────────────────────────

CREATE TABLE task_labels (
    task_id  UUID NOT NULL REFERENCES tasks (id),
    label_id UUID NOT NULL REFERENCES labels (id),
    PRIMARY KEY (task_id, label_id)
);

CREATE INDEX idx_task_labels_label_id ON task_labels (label_id);

-- ── Comments ──────────────────────────────────────────────────────────────────

CREATE TABLE comments (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    task_id    UUID        NOT NULL REFERENCES tasks (id),
    author_id  UUID        NOT NULL REFERENCES users (id),
    body       TEXT        NOT NULL,
    edited_at  TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_comments_task_id   ON comments (task_id);
CREATE INDEX idx_comments_author_id ON comments (author_id);
CREATE INDEX idx_comments_active    ON comments (task_id) WHERE deleted_at IS NULL;

-- ── Audit Log ─────────────────────────────────────────────────────────────────

CREATE TABLE audit_logs (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_type VARCHAR(50) NOT NULL,
    entity_id   UUID        NOT NULL,
    action      VARCHAR(50) NOT NULL,
    actor_id    UUID        REFERENCES users (id),
    payload     JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Primary access patterns: by entity (task history) and by actor (user activity)
CREATE INDEX idx_audit_logs_entity     ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_actor_id   ON audit_logs (actor_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at DESC);

-- ── Refresh Tokens ────────────────────────────────────────────────────────────

CREATE TABLE refresh_tokens (
    id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID         NOT NULL REFERENCES users (id),
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id    ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_token_hash ON refresh_tokens (token_hash);
-- Cleanup job queries expired + non-revoked tokens
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at) WHERE revoked_at IS NULL;
